version: '3'
#env_file: .env
services: 
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile${PHPVER}
    links:
     - mysql:mysql
    restart: always
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - VIRTUAL_HOST=${VIRTUAL_HOST}
     - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
     - ${WEBROOT}:/var/www/html
    networks:
      - web
      - internalnet
  
  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     #- MYSQL_DATABASE=joomla
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/xfer:/root/xfer
    networks:
      - internalnet

  smtpout:
    image: namshi/smtp
    restart: always
    environment
      - MAILNAME=${SMTPHOSTNAME}
    networks:
      - internalnet

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.8
#    restart: "no"
#    networks: 
#      - internalnet
#      - web
#    environment:
#      - PMA_HOST=mysql
#      - PMA_PORT=3306
#      - LETSENCRYPT_HOST=madm.ageplay.dk
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
#- VIRTUAL_HOST=madm.ageplay.dk
#      - VIRTUAL_PORT=80

networks: 
  web:
    external:
      name: ${PROXY_NETWORK}
  internalnet:
