version: '3'
#env_file: .env
services: 
  web:
    #image: joomla:3.6.2-apache-php7
    #image: joomla:3.6.2-apache
    build: 
      context: ./web
      dockerfile: Dockerfile${PHPVER}
    links:
     - mysql:mysql
    ports:
     - "${APP_PORT}:80"
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - VIRTUAL_HOST=${VIRTUAL_HOST}
     - VIRTUAL_PORT=${APP_PORT}
     - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
     - ${WEBROOT}:/var/www/html
    networks:
      - web
      - internalnet
  
  mysql:
    image: mysql:5.7.28
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     #- MYSQL_DATABASE=joomla
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/xfer:/root/xfer
    networks:
      - internalnet

  smtpout:
    image: namshi/smtp
    restart: always
    networks:
      - internalnet

networks: 
  web:
    external:
      name: ${PROXY_NETWORK}
  internalnet:
